#!/usr/bin/env python3
"""
Mac Mini Stats & Logs API
=========================
Serves system stats and service logs over HTTPS so the GitHub Pages
dashboard can fetch them over Tailscale without mixed-content errors.

Setup (run once on Mac mini):
    sudo tailscale cert my-biggest-beefsteak.tail437237.ts.net
    # Certs are saved to the current directory as .crt and .key files
    pip3 install -r requirements.txt

Usage:
    python3 server.py

Endpoints:
    GET /api/stats                          — CPU, RAM, Disk, uptime, network
    GET /api/services                       — per-service TCP health check
    GET /api/logs?service=immich&lines=50   — last N log lines

CORS is pre-configured for dao-xuan-thinh.github.io and localhost.
"""

import json
import socket
import ssl
import subprocess
import time
import os
from http.server import HTTPServer, BaseHTTPRequestHandler
from urllib.parse import urlparse, parse_qs

try:
    import psutil
except ImportError:
    print("ERROR: psutil not installed. Run:  pip3 install psutil")
    raise

# ── Configuration ──────────────────────────────────────────────────────────────

PORT = 9000

TAILSCALE_HOSTNAME = "my-biggest-beefsteak.tail437237.ts.net"

# Paths to TLS certificate files generated by `sudo tailscale cert <hostname>`
# tailscale cert saves them in the current working directory by default.
CERT_FILE = os.path.expanduser(f"~/{TAILSCALE_HOSTNAME}.crt")
KEY_FILE  = os.path.expanduser(f"~/{TAILSCALE_HOSTNAME}.key")

# Origins allowed to access the API.
# Add any extra origins here (e.g. other Tailscale devices you use).
ALLOWED_ORIGINS = [
    "https://dao-xuan-thinh.github.io",
    "http://localhost",
    "http://localhost:9000",
    "http://127.0.0.1",
    "null",  # file:// access during local dev
]

# ── Token Auth ────────────────────────────────────────────────────────────────
# All /api/* requests must include ?token=<API_TOKEN> in the query string.
# Change this to any long random string. Keep it private.
# Generate a new one with: python3 -c "import secrets; print(secrets.token_hex(24))"
API_TOKEN = "3df484b5a0a1fd711ba4438c1c6d8b79cc66444375e0da80"

# Per-service config.
# "docker"   : Docker container name (use `docker ps` to find it). Set to None to skip.
# "log_file" : Absolute path to a log file. Used if docker is None or docker logs fail.
# "port"     : Port on localhost to TCP-check for the health endpoint.
SERVICES = {
    "immich": {
        "name": "Immich",
        "docker": "immich_server",   # adjust to your actual container name
        "log_file": None,
        "port": 2283,
    },
    "openclaw": {
        "name": "OpenClaw",
        "docker": "openclaw",        # adjust to your actual container name
        "log_file": None,
        "port": 3000,
    },
    "projects": {
        "name": "Project Sites",
        "docker": None,
        "log_file": None,            # e.g. "/var/log/nginx/access.log"
        "port": 8080,
    },
    "proto": {
        "name": "Prototypes",
        "docker": None,
        "log_file": None,
        "port": 10000,
    },
}

# ── Helpers ────────────────────────────────────────────────────────────────────

def get_stats():
    cpu = psutil.cpu_percent(interval=0.5)
    ram = psutil.virtual_memory()
    disk = psutil.disk_usage("/")
    net_before = psutil.net_io_counters()
    time.sleep(0.5)
    net_after = psutil.net_io_counters()

    net_tx = round((net_after.bytes_sent - net_before.bytes_sent) / 1024, 1)  # KB/s
    net_rx = round((net_after.bytes_recv - net_before.bytes_recv) / 1024, 1)

    uptime_seconds = int(time.time() - psutil.boot_time())

    # Temperature — best effort; macOS M-series often returns empty dict
    temp = None
    try:
        temps = psutil.sensors_temperatures()
        if temps:
            all_temps = [t.current for group in temps.values() for t in group]
            if all_temps:
                temp = round(sum(all_temps) / len(all_temps), 1)
    except (AttributeError, NotImplementedError):
        pass

    return {
        "cpu":    round(cpu, 1),
        "ram":    round(ram.percent, 1),
        "disk":   round(disk.percent, 1),
        "uptime": uptime_seconds,
        "net_tx": net_tx,
        "net_rx": net_rx,
        "temp":   temp,
        "ram_used_gb":  round(ram.used / 1024**3, 2),
        "ram_total_gb": round(ram.total / 1024**3, 2),
    }


def check_service(port):
    """TCP connect to localhost:port — returns True if something is listening."""
    try:
        with socket.create_connection(("127.0.0.1", port), timeout=2):
            return True
    except OSError:
        return False


def get_services_status():
    result = []
    for key, svc in SERVICES.items():
        online = check_service(svc["port"]) if svc["port"] else False
        result.append({
            "id":     key,
            "name":   svc["name"],
            "port":   svc["port"],
            "online": online,
        })
    return result


def get_logs(service_key, lines=50):
    svc = SERVICES.get(service_key)
    if not svc:
        return {"error": f"Unknown service: {service_key}"}

    raw_lines = []

    # Try Docker first
    if svc.get("docker"):
        try:
            result = subprocess.run(
                ["docker", "logs", "--tail", str(lines), "--timestamps", svc["docker"]],
                capture_output=True, text=True, timeout=10,
            )
            # Docker sends logs to stderr by default
            combined = (result.stdout + result.stderr).strip()
            if combined:
                raw_lines = combined.splitlines()
        except (subprocess.TimeoutExpired, FileNotFoundError):
            pass

    # Fall back to log file
    if not raw_lines and svc.get("log_file") and os.path.exists(svc["log_file"]):
        try:
            result = subprocess.run(
                ["tail", "-n", str(lines), svc["log_file"]],
                capture_output=True, text=True, timeout=5,
            )
            raw_lines = result.stdout.strip().splitlines()
        except subprocess.TimeoutExpired:
            pass

    if not raw_lines:
        return {
            "service": service_key,
            "lines": [],
            "warning": "No log source available. Configure 'docker' container name or 'log_file' path in server.py SERVICES dict.",
        }

    parsed = []
    for line in raw_lines:
        parsed.append(parse_log_line(line))

    return {"service": service_key, "lines": parsed}


def parse_log_line(line):
    """
    Attempt to extract timestamp, level, and message from a log line.
    Handles Docker timestamped format and plain text logs.
    """
    line = line.strip()
    if not line:
        return None

    # Docker timestamp format: 2024-01-15T14:23:01.123456789Z  rest of log
    if len(line) > 30 and line[10] == "T" and "Z" in line[:35]:
        parts = line.split(" ", 1)
        ts_str = parts[0]
        rest = parts[1] if len(parts) > 1 else ""
        # Format time as HH:MM:SS
        try:
            ts_part = ts_str.split("T")[1][:8]
        except IndexError:
            ts_part = "??:??:??"
        level, msg = extract_level(rest)
        return {"time": ts_part, "level": level, "msg": msg or rest}

    # Plain line — no timestamp
    level, msg = extract_level(line)
    return {"time": "——", "level": level, "msg": msg or line}


LEVEL_KEYWORDS = {
    "ERROR": ["error", "err ", "exception", "critical", "fatal", "fail"],
    "WARN":  ["warn", "warning"],
    "DEBUG": ["debug", "trace", "verbose"],
    "INFO":  ["info"],
}

def extract_level(text):
    upper = text.upper()
    for level, keywords in LEVEL_KEYWORDS.items():
        for kw in keywords:
            if kw.upper() in upper:
                # Try to strip the level word from the start if present
                stripped = text
                for prefix in [f"[{level}]", f"{level}:", f" {level} "]:
                    if prefix in text.upper():
                        idx = text.upper().find(prefix) + len(prefix)
                        stripped = text[idx:].strip()
                        break
                return level, stripped
    return "INFO", text  # default to INFO


def json_response(handler, data, status=200):
    body = json.dumps(data, ensure_ascii=False).encode("utf-8")
    handler.send_response(status)
    handler.send_header("Content-Type", "application/json; charset=utf-8")
    handler.send_header("Content-Length", str(len(body)))
    set_cors(handler)
    handler.end_headers()
    handler.wfile.write(body)


def set_cors(handler):
    origin = handler.headers.get("Origin", "")
    if origin in ALLOWED_ORIGINS:
        handler.send_header("Access-Control-Allow-Origin", origin)
    else:
        # Deny — don't send CORS header
        pass
    handler.send_header("Access-Control-Allow-Methods", "GET, OPTIONS")
    handler.send_header("Access-Control-Allow-Headers", "Content-Type")
    handler.send_header("Vary", "Origin")


# ── Request Handler ────────────────────────────────────────────────────────────

class Handler(BaseHTTPRequestHandler):

    def log_message(self, fmt, *args):
        # Compact log format
        print(f"[{self.log_date_time_string()}] {self.address_string()} — {fmt % args}")

    def do_OPTIONS(self):
        self.send_response(204)
        set_cors(self)
        self.end_headers()

    def do_GET(self):
        parsed = urlparse(self.path)
        path = parsed.path.rstrip("/")
        qs = parse_qs(parsed.query)

        # Token check on all /api/* routes
        if path.startswith("/api/"):
            token = qs.get("token", [None])[0]
            if token != API_TOKEN:
                json_response(self, {"error": "Unauthorized"}, 401)
                return

        if path == "/api/stats":
            try:
                data = get_stats()
                json_response(self, data)
            except Exception as e:
                json_response(self, {"error": str(e)}, 500)

        elif path == "/api/services":
            try:
                data = get_services_status()
                json_response(self, data)
            except Exception as e:
                json_response(self, {"error": str(e)}, 500)

        elif path == "/api/logs":
            service = qs.get("service", ["immich"])[0]
            lines = int(qs.get("lines", ["50"])[0])
            lines = max(1, min(lines, 500))  # clamp 1–500
            try:
                data = get_logs(service, lines)
                data["lines"] = [l for l in data.get("lines", []) if l]  # remove None
                json_response(self, data)
            except Exception as e:
                json_response(self, {"error": str(e)}, 500)

        elif path in ("", "/"):
            self.send_response(200)
            self.send_header("Content-Type", "text/plain")
            self.end_headers()
            self.wfile.write(b"Mac Mini Stats API — OK\n")

        else:
            json_response(self, {"error": "Not found"}, 404)


# ── Entry Point ────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    server = HTTPServer(("0.0.0.0", PORT), Handler)

    # Wrap with TLS if cert files exist
    if os.path.exists(CERT_FILE) and os.path.exists(KEY_FILE):
        ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
        ctx.load_cert_chain(certfile=CERT_FILE, keyfile=KEY_FILE)
        server.socket = ctx.wrap_socket(server.socket, server_side=True)
        scheme = "https"
        print(f"TLS enabled — using {CERT_FILE}")
    else:
        scheme = "http"
        print(f"WARNING: cert files not found — running plain HTTP (will be blocked by browsers from HTTPS pages)")
        print(f"  Fix: run  sudo tailscale cert {TAILSCALE_HOSTNAME}  on your Mac mini")
        print(f"       then move the .crt/.key files to your home directory (~/).")

    print(f"Mac Mini Stats API running on port {PORT} ({scheme})")
    print(f"  API token: {API_TOKEN}")
    print(f"  Stats:    {scheme}://{TAILSCALE_HOSTNAME}:{PORT}/api/stats?token={API_TOKEN}")
    print(f"  Services: {scheme}://{TAILSCALE_HOSTNAME}:{PORT}/api/services?token={API_TOKEN}")
    print(f"  Logs:     {scheme}://{TAILSCALE_HOSTNAME}:{PORT}/api/logs?service=immich&lines=50&token={API_TOKEN}")
    print(f"")
    print(f"  Public URL (via Tailscale Funnel):")
    print(f"  https://{TAILSCALE_HOSTNAME}/api/stats?token={API_TOKEN}")
    print("Press Ctrl+C to stop.")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nStopped.")
